experimental:
  localPlugins:
    traefik-cone:
      moduleName: github.com/markuspi/traefik-cone

api:
  dashboard: true

providers:
  plugin:
    traefik-cone:
      expiration: 24h
      persistenceFilepath: /tmp/traefik-cone.json
  file:
    directory: /config/dynamic

entrypoints:
  web:
    address: ":80"
    asDefault: true
